---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pikube-mqtt
  namespace: hip
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: pikube-mqtt
  template:
    metadata:
      labels:
        application: pikube-mqtt
    spec:
      serviceAccountName: hip-operator
      containers:
        - name: pikube-mqtt
          image: silvertoken/pikube-mqtt:0.0.1